// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcP8ufnf-PcINC73jCRaMVVuPgVkTstaM',
    appId: '1:691918461618:web:67b97cbc6923c8d5bb87ab',
    messagingSenderId: '691918461618',
    projectId: 'path-intern',
    authDomain: 'path-intern.firebaseapp.com',
    storageBucket: 'path-intern.appspot.com',
    measurementId: 'G-CMKWZFHN0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCd7JzRMfGWmZHsVACHa0mOAKaOK8Kvg',
    appId: '1:691918461618:android:cbf6f58581c6b343bb87ab',
    messagingSenderId: '691918461618',
    projectId: 'path-intern',
    storageBucket: 'path-intern.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz3Am0Lab0Up2kzqfj1MEYBY5-tcKKmc4',
    appId: '1:691918461618:ios:0ef5cca3771336fcbb87ab',
    messagingSenderId: '691918461618',
    projectId: 'path-intern',
    storageBucket: 'path-intern.appspot.com',
    iosClientId: '691918461618-v31cnv9c86v1ld4e5ur7rlanjujdft37.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathInternMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz3Am0Lab0Up2kzqfj1MEYBY5-tcKKmc4',
    appId: '1:691918461618:ios:0ef5cca3771336fcbb87ab',
    messagingSenderId: '691918461618',
    projectId: 'path-intern',
    storageBucket: 'path-intern.appspot.com',
    iosClientId: '691918461618-v31cnv9c86v1ld4e5ur7rlanjujdft37.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathInternMobile',
  );
}
